// AUTO-GENERATED by scripts/generate-embeddings.ts — do not edit by hand.
// Models: Xenova/all-MiniLM-L6-v2 (384d), Xenova/bge-small-en-v1.5 (384d).
// All vectors are L2-normalized at encode time.
// biome-ignore-all lint/suspicious/noApproximativeNumericConstant: PCA coords may incidentally resemble math constants

export type ConceptCategory =
	| "animals"
	| "foods"
	| "programming"
	| "emotions"
	| "countries";

export interface Concept {
	text: string;
	category: ConceptCategory;
}

export const CONCEPTS: readonly Concept[] = [
	{
		text: "dog",
		category: "animals",
	},
	{
		text: "cat",
		category: "animals",
	},
	{
		text: "horse",
		category: "animals",
	},
	{
		text: "elephant",
		category: "animals",
	},
	{
		text: "dolphin",
		category: "animals",
	},
	{
		text: "eagle",
		category: "animals",
	},
	{
		text: "pizza",
		category: "foods",
	},
	{
		text: "sushi",
		category: "foods",
	},
	{
		text: "pasta",
		category: "foods",
	},
	{
		text: "burger",
		category: "foods",
	},
	{
		text: "salad",
		category: "foods",
	},
	{
		text: "sandwich",
		category: "foods",
	},
	{
		text: "Python",
		category: "programming",
	},
	{
		text: "JavaScript",
		category: "programming",
	},
	{
		text: "Rust",
		category: "programming",
	},
	{
		text: "TypeScript",
		category: "programming",
	},
	{
		text: "Go",
		category: "programming",
	},
	{
		text: "Haskell",
		category: "programming",
	},
	{
		text: "joy",
		category: "emotions",
	},
	{
		text: "sadness",
		category: "emotions",
	},
	{
		text: "anger",
		category: "emotions",
	},
	{
		text: "fear",
		category: "emotions",
	},
	{
		text: "love",
		category: "emotions",
	},
	{
		text: "surprise",
		category: "emotions",
	},
	{
		text: "France",
		category: "countries",
	},
	{
		text: "Japan",
		category: "countries",
	},
	{
		text: "Brazil",
		category: "countries",
	},
	{
		text: "Germany",
		category: "countries",
	},
	{
		text: "Egypt",
		category: "countries",
	},
	{
		text: "Canada",
		category: "countries",
	},
] as const;

export const CONCEPT_PCA_2D: readonly (readonly [number, number])[] = [
	[-0.0382, -0.0589],
	[-0.0895, -0.0168],
	[-0.0922, -0.0727],
	[-0.0508, -0.0501],
	[-0.0198, -0.0513],
	[-0.0054, 0.0281],
	[-0.2328, -0.1359],
	[-0.1587, 0.0131],
	[-0.312, -0.0129],
	[-0.059, -0.2514],
	[-0.2778, -0.1247],
	[-0.1245, -0.1362],
	[-0.0576, 0.3277],
	[-0.0167, 0.6018],
	[-0.2227, -0.0168],
	[-0.0232, 0.7911],
	[-0.1928, -0.0081],
	[-0.1462, 0.4741],
	[-0.1879, -0.138],
	[-0.1927, -0.2168],
	[-0.1895, -0.1976],
	[-0.1904, -0.1351],
	[-0.2468, -0.1949],
	[-0.1416, -0.0936],
	[0.5886, -0.1059],
	[0.4873, -0.03],
	[0.6198, -0.073],
	[0.6218, -0.057],
	[0.4137, 0.0479],
	[0.5375, -0.1061],
] as const;

// top-3 nearest neighbors per concept (indices into CONCEPTS), with cosine scores.
// Computed in full 384-d space (NOT from the 2-d projection).
export const CONCEPT_NEIGHBORS: readonly { j: number; score: number }[][] = [
	[
		{ j: 1, score: 0.659 },
		{ j: 2, score: 0.5465 },
		{ j: 3, score: 0.5369 },
	],
	[
		{ j: 0, score: 0.659 },
		{ j: 3, score: 0.4916 },
		{ j: 2, score: 0.4177 },
	],
	[
		{ j: 0, score: 0.5465 },
		{ j: 3, score: 0.5378 },
		{ j: 4, score: 0.4524 },
	],
	[
		{ j: 2, score: 0.5378 },
		{ j: 0, score: 0.5369 },
		{ j: 1, score: 0.4916 },
	],
	[
		{ j: 2, score: 0.4524 },
		{ j: 0, score: 0.4521 },
		{ j: 3, score: 0.4492 },
	],
	[
		{ j: 4, score: 0.4056 },
		{ j: 3, score: 0.4009 },
		{ j: 2, score: 0.385 },
	],
	[
		{ j: 8, score: 0.5986 },
		{ j: 10, score: 0.5648 },
		{ j: 11, score: 0.5091 },
	],
	[
		{ j: 25, score: 0.4362 },
		{ j: 6, score: 0.4167 },
		{ j: 10, score: 0.3937 },
	],
	[
		{ j: 6, score: 0.5986 },
		{ j: 10, score: 0.5356 },
		{ j: 14, score: 0.5227 },
	],
	[
		{ j: 11, score: 0.6388 },
		{ j: 6, score: 0.4808 },
		{ j: 10, score: 0.4462 },
	],
	[
		{ j: 6, score: 0.5648 },
		{ j: 8, score: 0.5356 },
		{ j: 11, score: 0.5096 },
	],
	[
		{ j: 9, score: 0.6388 },
		{ j: 10, score: 0.5096 },
		{ j: 6, score: 0.5091 },
	],
	[
		{ j: 1, score: 0.3818 },
		{ j: 0, score: 0.3566 },
		{ j: 8, score: 0.3466 },
	],
	[
		{ j: 15, score: 0.4099 },
		{ j: 12, score: 0.3076 },
		{ j: 0, score: 0.2917 },
	],
	[
		{ j: 8, score: 0.5227 },
		{ j: 2, score: 0.3743 },
		{ j: 6, score: 0.371 },
	],
	[
		{ j: 13, score: 0.4099 },
		{ j: 17, score: 0.2459 },
		{ j: 0, score: 0.1715 },
	],
	[
		{ j: 22, score: 0.3015 },
		{ j: 0, score: 0.2895 },
		{ j: 1, score: 0.2887 },
	],
	[
		{ j: 12, score: 0.3338 },
		{ j: 1, score: 0.3047 },
		{ j: 8, score: 0.3017 },
	],
	[
		{ j: 22, score: 0.4891 },
		{ j: 20, score: 0.4631 },
		{ j: 19, score: 0.393 },
	],
	[
		{ j: 20, score: 0.4067 },
		{ j: 18, score: 0.393 },
		{ j: 22, score: 0.3398 },
	],
	[
		{ j: 18, score: 0.4631 },
		{ j: 21, score: 0.4352 },
		{ j: 19, score: 0.4067 },
	],
	[
		{ j: 20, score: 0.4352 },
		{ j: 22, score: 0.4216 },
		{ j: 18, score: 0.3863 },
	],
	[
		{ j: 18, score: 0.4891 },
		{ j: 21, score: 0.4216 },
		{ j: 1, score: 0.3978 },
	],
	[
		{ j: 18, score: 0.3317 },
		{ j: 14, score: 0.3274 },
		{ j: 8, score: 0.316 },
	],
	[
		{ j: 27, score: 0.7434 },
		{ j: 26, score: 0.6519 },
		{ j: 29, score: 0.6469 },
	],
	[
		{ j: 27, score: 0.6665 },
		{ j: 26, score: 0.6456 },
		{ j: 29, score: 0.5999 },
	],
	[
		{ j: 27, score: 0.7566 },
		{ j: 24, score: 0.6519 },
		{ j: 25, score: 0.6456 },
	],
	[
		{ j: 26, score: 0.7566 },
		{ j: 24, score: 0.7434 },
		{ j: 25, score: 0.6665 },
	],
	[
		{ j: 29, score: 0.5147 },
		{ j: 24, score: 0.4902 },
		{ j: 27, score: 0.4827 },
	],
	[
		{ j: 24, score: 0.6469 },
		{ j: 27, score: 0.6375 },
		{ j: 25, score: 0.5999 },
	],
] as const;

export const SENTENCE_POOL: readonly string[] = [
	"The cat sat on the warm windowsill watching birds.",
	"A kitten napped in the sunny window.",
	"The dog chased a ball across the park.",
	"Puppies love to play fetch outside.",
	"Python is a popular language for data science.",
	"JavaScript runs in every modern web browser.",
	"Rust offers memory safety without garbage collection.",
	"The compiler caught a type error at build time.",
	"She felt overwhelming joy at the news.",
	"He was deeply saddened by the loss.",
	"The recipe calls for flour, sugar, and eggs.",
	"I ordered a pepperoni pizza for dinner.",
	"Tokyo is the capital of Japan.",
	"Paris is the capital of France.",
	"The train arrived twenty minutes late.",
	"My flight was delayed by half an hour.",
	"Quantum computing uses qubits instead of classical bits.",
	"Neural networks learn patterns from large datasets.",
	"The stock market closed higher on Friday.",
	"Interest rates rose by a quarter point.",
] as const;

// pairwise cosine matrix for the sentence pool (full 384-d).
export const SENTENCE_COSINE: readonly (readonly number[])[] = [
	[
		1, 0.5317, 0.1125, 0.1998, 0.0093, 0.0049, -0.0673, -0.0014, 0.2046, 0.0743,
		-0.0013, 0.027, -0.1157, -0.1312, 0.0116, 0.0898, 0.0614, 0.0332, 0.0185,
		0.0188,
	],
	[
		0.5317, 1, 0.1191, 0.234, -0.0184, 0.0732, 0.0645, 0.1139, 0.1673, 0.0492,
		-0.0479, 0.0219, -0.0339, -0.0572, 0.0811, 0.0965, -0.047, -0.0197, 0.0564,
		0.0818,
	],
	[
		0.1125, 0.1191, 1, 0.3044, -0.0016, 0.1458, -0.0535, 0.0295, 0.0831, 0.0889,
		-0.0368, 0.0873, 0.0685, -0.0176, 0.1268, 0.1421, -0.0767, 0, 0.0377,
		0.0731,
	],
	[
		0.1998, 0.234, 0.3044, 1, 0.0566, 0.1331, 0.1114, -0.0285, 0.137, 0.0252,
		0.0462, 0.104, 0.0017, 0.0106, 0.0494, -0.0375, 0.0568, 0.1048, -0.0201,
		0.08,
	],
	[
		0.0093, -0.0184, -0.0016, 0.0566, 1, 0.136, 0.0588, 0.0779, 0.0329, 0.0279,
		-0.0296, 0.034, 0.002, 0.0402, -0.0792, -0.0148, 0.1586, 0.1956, 0.036,
		0.023,
	],
	[
		0.0049, 0.0732, 0.1458, 0.1331, 0.136, 1, 0.1086, 0.0953, 0.0164, -0.0226,
		0.0584, -0.0098, 0.0948, -0.0053, -0.0757, -0.0461, 0.1998, 0.0766, 0.0979,
		0.0009,
	],
	[
		-0.0673, 0.0645, -0.0535, 0.1114, 0.0588, 0.1086, 1, 0.2171, 0.026, 0.034,
		-0.0084, -0.0171, 0.1113, -0.1115, 0.0444, -0.1011, 0.1219, 0.054, 0.0582,
		0.0098,
	],
	[
		-0.0014, 0.1139, 0.0295, -0.0285, 0.0779, 0.0953, 0.2171, 1, 0.0925, 0.105,
		-0.0028, 0.0628, 0.01, -0.0155, 0.0844, 0.1571, 0.0928, -0.0568, 0.0856,
		-0.0057,
	],
	[
		0.2046, 0.1673, 0.0831, 0.137, 0.0329, 0.0164, 0.026, 0.0925, 1, 0.4219,
		0.0079, 0.1053, 0.0567, 0.0159, 0.0405, 0.1457, 0.0447, -0.0159, 0.0787,
		0.0764,
	],
	[
		0.0743, 0.0492, 0.0889, 0.0252, 0.0279, -0.0226, 0.034, 0.105, 0.4219, 1,
		-0.0171, 0.0396, 0.0031, -0.0021, 0.1124, 0.1279, -0.0179, -0.0392, 0.1241,
		0.0471,
	],
	[
		-0.0013, -0.0479, -0.0368, 0.0462, -0.0296, 0.0584, -0.0084, -0.0028,
		0.0079, -0.0171, 1, 0.2606, 0.0134, 0.0983, -0.0161, 0.006, 0.0164, 0.0587,
		-0.0408, -0.0656,
	],
	[
		0.027, 0.0219, 0.0873, 0.104, 0.034, -0.0098, -0.0171, 0.0628, 0.1053,
		0.0396, 0.2606, 1, 0.0296, 0.04, 0.0559, 0.2218, 0.012, 0.0703, 0.029,
		0.0562,
	],
	[
		-0.1157, -0.0339, 0.0685, 0.0017, 0.002, 0.0948, 0.1113, 0.01, 0.0567,
		0.0031, 0.0134, 0.0296, 1, 0.2076, 0.0259, 0.0292, 0.0493, 0.0408, 0.1399,
		0.0271,
	],
	[
		-0.1312, -0.0572, -0.0176, 0.0106, 0.0402, -0.0053, -0.1115, -0.0155,
		0.0159, -0.0021, 0.0983, 0.04, 0.2076, 1, -0.0147, -0.0169, -0.0096, 0.0526,
		0.0569, -0.0502,
	],
	[
		0.0116, 0.0811, 0.1268, 0.0494, -0.0792, -0.0757, 0.0444, 0.0844, 0.0405,
		0.1124, -0.0161, 0.0559, 0.0259, -0.0147, 1, 0.3201, -0.0922, -0.0275,
		0.0665, 0.0494,
	],
	[
		0.0898, 0.0965, 0.1421, -0.0375, -0.0148, -0.0461, -0.1011, 0.1571, 0.1457,
		0.1279, 0.006, 0.2218, 0.0292, -0.0169, 0.3201, 1, 0.035, -0.0207, 0.1557,
		0.1047,
	],
	[
		0.0614, -0.047, -0.0767, 0.0568, 0.1586, 0.1998, 0.1219, 0.0928, 0.0447,
		-0.0179, 0.0164, 0.012, 0.0493, -0.0096, -0.0922, 0.035, 1, 0.112, 0.0302,
		0.0756,
	],
	[
		0.0332, -0.0197, 0, 0.1048, 0.1956, 0.0766, 0.054, -0.0568, -0.0159,
		-0.0392, 0.0587, 0.0703, 0.0408, 0.0526, -0.0275, -0.0207, 0.112, 1, 0.0245,
		0.0259,
	],
	[
		0.0185, 0.0564, 0.0377, -0.0201, 0.036, 0.0979, 0.0582, 0.0856, 0.0787,
		0.1241, -0.0408, 0.029, 0.1399, 0.0569, 0.0665, 0.1557, 0.0302, 0.0245, 1,
		0.1909,
	],
	[
		0.0188, 0.0818, 0.0731, 0.08, 0.023, 0.0009, 0.0098, -0.0057, 0.0764,
		0.0471, -0.0656, 0.0562, 0.0271, -0.0502, 0.0494, 0.1047, 0.0756, 0.0259,
		0.1909, 1,
	],
] as const;

export interface AnalogyResult {
	a: string;
	b: string;
	c: string;
	expected: string;
	top: { word: string; score: number }[];
}

// (a - b + c) → top-5 nearest neighbors in ANALOGY_VOCAB (excluding a, b, c).
// Computed on Xenova/all-MiniLM-L6-v2 — a modern sentence-transformer.
// These results illustrate that linear analogy arithmetic DOES NOT
// reliably recover the expected word on contextual embeddings.
export const ANALOGY_RESULTS: readonly AnalogyResult[] = [
	{
		a: "king",
		b: "man",
		c: "woman",
		expected: "queen",
		top: [
			{
				word: "queen",
				score: 0.5776,
			},
			{
				word: "actress",
				score: 0.4981,
			},
			{
				word: "mother",
				score: 0.4615,
			},
			{
				word: "princess",
				score: 0.4228,
			},
			{
				word: "prince",
				score: 0.3871,
			},
		],
	},
	{
		a: "father",
		b: "man",
		c: "woman",
		expected: "mother",
		top: [
			{
				word: "mother",
				score: 0.6533,
			},
			{
				word: "actress",
				score: 0.5171,
			},
			{
				word: "aunt",
				score: 0.4172,
			},
			{
				word: "actor",
				score: 0.3473,
			},
			{
				word: "queen",
				score: 0.3375,
			},
		],
	},
	{
		a: "Paris",
		b: "France",
		c: "Japan",
		expected: "Tokyo",
		top: [
			{
				word: "Tokyo",
				score: 0.8395,
			},
			{
				word: "Berlin",
				score: 0.478,
			},
			{
				word: "Rome",
				score: 0.4212,
			},
			{
				word: "Germany",
				score: 0.3902,
			},
			{
				word: "Italy",
				score: 0.3848,
			},
		],
	},
] as const;

export const COMPARISON_SENTENCES: readonly string[] = [
	"The cat slept on the mat.",
	"A dog barked at the mailman.",
	"Python is a programming language.",
	"JavaScript runs in the browser.",
	"I love eating pizza on Fridays.",
	"Sushi is my favorite Japanese food.",
	"Tokyo is a vibrant city.",
	"Paris has beautiful architecture.",
	"She felt deep happiness today.",
	"He was angry about the delay.",
	"Machine learning needs large datasets.",
	"The compiler reported a syntax error.",
	"Eagles soar high above the mountains.",
	"Elephants are highly intelligent animals.",
	"The recipe needs fresh basil leaves.",
] as const;

export const COMPARISON_MINILM_PCA_2D: readonly (readonly [number, number])[] =
	[
		[0.2374, -0.3746],
		[0.2846, -0.0981],
		[0.5045, 0.108],
		[0.4128, 0.1316],
		[-0.2126, -0.4375],
		[-0.4598, -0.3267],
		[-0.5195, 0.1271],
		[-0.4481, 0.3195],
		[-0.1066, -0.224],
		[0.3198, -0.2378],
		[0.0234, 0.4682],
		[0.4649, 0.0136],
		[-0.1733, 0.2756],
		[-0.0487, 0.5548],
		[-0.2789, -0.2997],
	] as const;
export const COMPARISON_MPNET_PCA_2D: readonly (readonly [number, number])[] = [
	[-0.2693, -0.4393],
	[-0.3426, -0.4174],
	[-0.206, 0.411],
	[-0.2679, 0.3472],
	[0.2066, -0.1563],
	[0.3417, -0.0107],
	[0.4995, 0.1177],
	[0.4582, 0.1387],
	[0.189, -0.3583],
	[-0.3854, -0.1813],
	[-0.0506, 0.3904],
	[-0.4247, 0.3025],
	[0.1197, -0.0854],
	[0.2222, -0.0609],
	[-0.0905, 0.0019],
] as const;

export const COMPARISON_MINILM_NEIGHBORS: readonly {
	j: number;
	score: number;
}[][] = [
	[
		{ j: 1, score: 0.1638 },
		{ j: 8, score: 0.1275 },
		{ j: 9, score: 0.0867 },
	],
	[
		{ j: 0, score: 0.1638 },
		{ j: 9, score: 0.1293 },
		{ j: 13, score: 0.1065 },
	],
	[
		{ j: 11, score: 0.3318 },
		{ j: 3, score: 0.2488 },
		{ j: 10, score: 0.1514 },
	],
	[
		{ j: 2, score: 0.2488 },
		{ j: 11, score: 0.2066 },
		{ j: 13, score: 0.1081 },
	],
	[
		{ j: 5, score: 0.305 },
		{ j: 14, score: 0.1743 },
		{ j: 8, score: 0.1658 },
	],
	[
		{ j: 6, score: 0.3421 },
		{ j: 4, score: 0.305 },
		{ j: 14, score: 0.2281 },
	],
	[
		{ j: 7, score: 0.3432 },
		{ j: 5, score: 0.3421 },
		{ j: 8, score: 0.1913 },
	],
	[
		{ j: 6, score: 0.3432 },
		{ j: 12, score: 0.1923 },
		{ j: 13, score: 0.1778 },
	],
	[
		{ j: 6, score: 0.1913 },
		{ j: 4, score: 0.1658 },
		{ j: 9, score: 0.1408 },
	],
	[
		{ j: 11, score: 0.144 },
		{ j: 8, score: 0.1408 },
		{ j: 1, score: 0.1293 },
	],
	[
		{ j: 13, score: 0.2407 },
		{ j: 2, score: 0.1514 },
		{ j: 7, score: 0.1196 },
	],
	[
		{ j: 2, score: 0.3318 },
		{ j: 3, score: 0.2066 },
		{ j: 9, score: 0.144 },
	],
	[
		{ j: 13, score: 0.2459 },
		{ j: 7, score: 0.1923 },
		{ j: 4, score: 0.0719 },
	],
	[
		{ j: 12, score: 0.2459 },
		{ j: 10, score: 0.2407 },
		{ j: 7, score: 0.1778 },
	],
	[
		{ j: 5, score: 0.2281 },
		{ j: 4, score: 0.1743 },
		{ j: 7, score: 0.1517 },
	],
] as const;
export const COMPARISON_MPNET_NEIGHBORS: readonly {
	j: number;
	score: number;
}[][] = [
	[
		{ j: 8, score: 0.4806 },
		{ j: 1, score: 0.4273 },
		{ j: 4, score: 0.3732 },
	],
	[
		{ j: 9, score: 0.5001 },
		{ j: 0, score: 0.4273 },
		{ j: 13, score: 0.3994 },
	],
	[
		{ j: 11, score: 0.5972 },
		{ j: 10, score: 0.5928 },
		{ j: 3, score: 0.5399 },
	],
	[
		{ j: 11, score: 0.5454 },
		{ j: 2, score: 0.5399 },
		{ j: 14, score: 0.3813 },
	],
	[
		{ j: 5, score: 0.6048 },
		{ j: 8, score: 0.4649 },
		{ j: 7, score: 0.4178 },
	],
	[
		{ j: 4, score: 0.6048 },
		{ j: 6, score: 0.5896 },
		{ j: 8, score: 0.4781 },
	],
	[
		{ j: 7, score: 0.6835 },
		{ j: 5, score: 0.5896 },
		{ j: 8, score: 0.4871 },
	],
	[
		{ j: 6, score: 0.6835 },
		{ j: 13, score: 0.5017 },
		{ j: 8, score: 0.4896 },
	],
	[
		{ j: 7, score: 0.4896 },
		{ j: 6, score: 0.4871 },
		{ j: 0, score: 0.4806 },
	],
	[
		{ j: 11, score: 0.5112 },
		{ j: 1, score: 0.5001 },
		{ j: 14, score: 0.4127 },
	],
	[
		{ j: 2, score: 0.5928 },
		{ j: 13, score: 0.4648 },
		{ j: 11, score: 0.453 },
	],
	[
		{ j: 2, score: 0.5972 },
		{ j: 3, score: 0.5454 },
		{ j: 9, score: 0.5112 },
	],
	[
		{ j: 13, score: 0.4626 },
		{ j: 7, score: 0.4598 },
		{ j: 8, score: 0.405 },
	],
	[
		{ j: 7, score: 0.5017 },
		{ j: 2, score: 0.4797 },
		{ j: 6, score: 0.4698 },
	],
	[
		{ j: 10, score: 0.4473 },
		{ j: 11, score: 0.4466 },
		{ j: 5, score: 0.4418 },
	],
] as const;

export const MODEL_INFO = {
	minilm: {
		name: "all-MiniLM-L6-v2",
		dims: 384,
		family: "Sentence-Transformers",
	},
	bge: { name: "bge-small-en-v1.5", dims: 384, family: "BAAI" },
} as const;
