/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as EventLoopRouteImport } from './routes/event-loop'
import { Route as CriticalRenderingPathRouteImport } from './routes/critical-rendering-path'
import { Route as IndexRouteImport } from './routes/index'

const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const EventLoopRoute = EventLoopRouteImport.update({
  id: '/event-loop',
  path: '/event-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticalRenderingPathRoute = CriticalRenderingPathRouteImport.update({
  id: '/critical-rendering-path',
  path: '/critical-rendering-path',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/critical-rendering-path': typeof CriticalRenderingPathRoute
  '/event-loop': typeof EventLoopRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/critical-rendering-path': typeof CriticalRenderingPathRoute
  '/event-loop': typeof EventLoopRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/critical-rendering-path': typeof CriticalRenderingPathRoute
  '/event-loop': typeof EventLoopRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/critical-rendering-path'
    | '/event-loop'
    | '/reconciliation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/critical-rendering-path' | '/event-loop' | '/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/critical-rendering-path'
    | '/event-loop'
    | '/reconciliation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriticalRenderingPathRoute: typeof CriticalRenderingPathRoute
  EventLoopRoute: typeof EventLoopRoute
  ReconciliationRoute: typeof ReconciliationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-loop': {
      id: '/event-loop'
      path: '/event-loop'
      fullPath: '/event-loop'
      preLoaderRoute: typeof EventLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critical-rendering-path': {
      id: '/critical-rendering-path'
      path: '/critical-rendering-path'
      fullPath: '/critical-rendering-path'
      preLoaderRoute: typeof CriticalRenderingPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriticalRenderingPathRoute: CriticalRenderingPathRoute,
  EventLoopRoute: EventLoopRoute,
  ReconciliationRoute: ReconciliationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
